inherit_from: .rubocop_prettier.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/graphql/queries/**/*
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
