AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: False
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
